config/routes.rb
Rails.application.routes.draw do
  resources :packets do
    collection { post :import }
    resources :products do
      collection { post :import }
    end
  end
  devise_for :user7s, controllers: { registrations: "users/registrations" }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#show'
  get 'home/inactive' => 'home#inactive'
  get 'home/ftpguides' => 'home#ftpguides'
  get 'home/websiteguides' => 'home#websiteguides'
end

app/models/packet.rb
class Packet < ApplicationRecord
  belongs_to :user, :foreign_key => "user_id"
  has_many :products, inverse_of: :packet, :dependent => :destroy
  validate :mandatory_validation
  validate :recall_validation
  validate :usda_2_validation
  validate :usda_3_validation

  def self.to_csv
    attributes = %w{vendor_number company_name primary_contact phone_1 phone_2 email ops_name ops_phone_1 ops_phone_2 ops_email qa_name qa_phone_1 qa_phone_2 qa_email haccp_1_type haccp_1_company problems_2 haccp_1_score haccp_1_expires haccp_1_scheduled haccp_2_type haccp_2_company problems_3 haccp_2_score haccp_2_expires haccp_2_scheduled}
    CSV.generate(headers: true) do |csv|
      csv << attributes
      all.each do |packet|
        csv << packet.attributes.values_at(*attributes)
      end
    end
  end

  def mandatory_validation
    if additional_integer_1 == 1
      if !primary_contact.present?
        errors.add(:primary_contact, "is required")
      end
      if !phone_1.present?
        errors.add(:phone_1, "is required")
      end
      if !email.present?
        errors.add(:email, "is required")
      end
      if !qa_name.present?
        errors.add(:qa_name, "is required")
      end
      if !qa_phone_1.present?
        errors.add(:qa_phone_1, "is required")
      end
      if !qa_email.present?
        errors.add(:qa_email, "is required")
      end
      if !ops_name.present?
        errors.add(:ops_name, "is required")
      end
      if !ops_phone_1.present?
        errors.add(:ops_phone_1, "is required")
      end
      if !ops_email.present?
        errors.add(:ops_email, "is required")
      end
      if !usda_establishment_number_1.present?
        errors.add(:usda_establishment_number_1, "is required")
      end
      if !usda_establishment_name_1.present?
        errors.add(:usda_establishment_name_1, "is required")
      end
      if !mock_recall_sop_1.present?
        errors.add(:mock_recall_sop_1, "is required")
      end
      if !mock_recall_date_1.present?
        errors.add(:mock_recall_date_1, "is required")
      end
      if !bone_foreign_1.present?
        errors.add(:bone_foreign_1, "is required")
      end
      if !complaint_1.present?
        errors.add(:complaint_1, "is required")
      end
      if !haccp_1_certificate.present?
        errors.add(:haccp_1_certificate, "is required")
      end
      if !haccp_1_expires.present?
        errors.add(:haccp_1_expires, "is required")
      end
      if !haccp_1_scheduled.present?
        errors.add(:haccp_1_scheduled, "is required")
      end
      if !problems_2.present?
        errors.add(:problems_2, "is required")
      end
      if !haccp_1_type.present?
        errors.add(:haccp_1_type, "is required")
      end
      if !haccp_1_company.present?
        errors.add(:haccp_1_company, "is required")
      end
      if !haccp_1_score.present?
        errors.add(:haccp_1_score, "is required")
      end
      if !additional_string_1.present?
        errors.add(:additional_string_1, "is required")
      end
      if !additional_string_2.present?
        errors.add(:additional_string_2, "is required")
      end
      if !website.present?
        errors.add(:website, "is required")
      end
      if !non_disclosure.present?
        errors.add(:non_disclosure, "is required")
      end
      if !w9.present?
        errors.add(:w9, "is required")
      end
      if !liability.present?
        errors.add(:liability, "is required")
      end
      if !guarantee.present?
        errors.add(:guarantee, "is required")
      end
    end
  end

  def recall_validation
    if additional_integer_1 == 1 && !errors.any?
      if recall_this_year_1.present? && !recall_1.present?
        errors.add(:recall_1, "documentation is required")
      end
      if recall_this_year_2.present? && !recall_2.present?
        errors.add(:recall_2, "documentation is required")
      end
      if recall_this_year_3.present? && !recall_3.present?
        errors.add(:recall_3, "documentation is required")
      end
    end
  end

  def usda_2_validation
    if additional_integer_1 == 1 && !errors.any?
      if usda_establishment_number_2.present?
        if !usda_establishment_name_2.present?
          errors.add(:usda_establishment_name_2, "is required")
        end
        if !mock_recall_sop_2.present?
          errors.add(:mock_recall_sop_2, "is required")
        end
        if !mock_recall_date_2.present?
          errors.add(:mock_recall_date_2, "is required")
        end
        if !bone_foreign_2.present?
          errors.add(:bone_foreign_2, "is required")
        end
        if !complaint_2.present?
          errors.add(:complaint_2, "is required")
        end
        if !haccp_2_certificate.present?
          errors.add(:haccp_2_certificate, "is required")
        end
        if !haccp_2_expires.present?
          errors.add(:haccp_2_expires, "is required")
        end
        if !haccp_2_scheduled.present?
          errors.add(:haccp_2_scheduled, "is required")
        end
        if !problems_3.present?
          errors.add(:problems_3, "is required")
        end
        if !haccp_2_type.present?
          errors.add(:haccp_2_type, "is required")
        end
        if !haccp_2_company.present?
          errors.add(:haccp_2_company, "is required")
        end
        if !haccp_2_score.present?
          errors.add(:haccp_2_score, "is required")
        end
        if !additional_string_3.present?
          errors.add(:additional_string_3, "is required")
        end
        if !additional_string_4.present?
          errors.add(:additional_string_4, "is required")
        end
      end
    end
  end

  def usda_3_validation
    if additional_integer_1 == 1 && !errors.any?
      if usda_establishment_number_3.present?
        if !usda_establishment_name_3.present?
          errors.add(:usda_establishment_name_3, "is required")
        end
        if !mock_recall_sop_3.present?
          errors.add(:mock_recall_sop_3, "is required")
        end
        if !mock_recall_date_3.present?
          errors.add(:mock_recall_date_3, "is required")
        end
        if !bone_foreign_3.present?
          errors.add(:bone_foreign_3, "is required")
        end
        if !complaint_3.present?
          errors.add(:complaint_3, "is required")
        end
        if !haccp_3_certificate.present?
          errors.add(:haccp_3_certificate, "is required")
        end
        if !haccp_3_expires.present?
          errors.add(:haccp_3_expires, "is required")
        end
        if !haccp_3_scheduled.present?
          errors.add(:haccp_3_scheduled, "is required")
        end
        if !qa_phone_1_ext.present?
          errors.add(:qa_phone_1_ext, "is required")
        end
        if !haccp_3_type.present?
          errors.add(:haccp_3_type, "is required")
        end
        if !haccp_3_company.present?
          errors.add(:haccp_3_company, "is required")
        end
        if !haccp_3_score.present?
          errors.add(:haccp_3_score, "is required")
        end
        if !additional_string_5.present?
          errors.add(:additional_string_5, "is required")
        end
        if !problems_1.present?
          errors.add(:problems_1, "is required")
        end
      end
    end
  end

  def self.import(file)
    CSV.foreach(file.path, headers:true) do |row|
      Packet.create! row.to_hash
    end
  end

end

app/controllers/packets_controller.rb
class PacketsController < ApplicationController
  before_action :set_packet, only: [:show, :edit, :update, :destroy]

  # GET /packets
  def index
    if current_user7.admin?
      @packets = Packet.all
    else
      @packets = Packet.where("user_id = ?", current_user7.id)
    end
    respond_to do |format|
      format.html
      format.csv { send_data @packets.to_csv }
    end
  end

  # GET /packets/1
  def show
  end

  # GET /packets/new
  def new
    @packet = Packet.new
  end

  # GET /packets/1/edit
  def edit
    if !current_user7.admin?
      @packet = Packet.where("user_id = ?", current_user7.id).last
      if @packet.completed
        redirect_to @packet, notice: 'Packet is now read only.'
      end
    end
  end

  # POST /packets
  def create
    @packet = Packet.new(packet_params)
    @packet.user_id = current_user7.id
    respond_to do |format|
      if @packet.save
        format.html { redirect_to @packet, notice: 'Packet was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /packets/1
  def update
    respond_to do |format|
      if @packet.update(packet_params)
        format.html { redirect_to @packet, notice: 'Packet was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /packets/1
  def destroy
    @packet.destroy
    respond_to do |format|
      format.html { redirect_to packets_url, notice: 'Packet was successfully destroyed.' }
    end
  end

  def import
    Packet.import(params[:file])
    redirect_to root_url, notice: "Packets imported."
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_packet
      @packet = Packet.find(params[:id])
      unless current_user7.id == @packet.user_id || current_user7.admin?
       redirect_to root_path, :alert => "Access denied."
      end
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def packet_params
      params.require(:packet).permit(:user_id, :packet_number, :vendor_number, :requested_date, :due_date, :completed, :company_name, :company_type, :dba, :address_1, :address_2, :city, :zip, :state, :cntry_code, :ship_address_1, :ship_address_2, :ship_city, :ship_zip, :ship_state, :primary_contact, :phone_1, :phone_2, :email, :fax, :website, :qa_name, :qa_phone_1, :qa_phone_1_ext, :qa_phone_2, :qa_email, :ops_name, :ops_phone_1, :ops_phone_1_ext, :ops_phone_2, :ops_email, :notes,  :usda_establishment_name_1, :usda_establishment_number_1, :mock_recall_sop_1, :mock_recall_date_1, :recall_this_year_1, :recall_1, :bone_foreign_1, :complaint_1, :problems_1, :haccp_1_certificate, :haccp_1_type, :haccp_1_company, :haccp_1_score, :haccp_1_expires, :haccp_1_scheduled, :usda_establishment_name_2, :usda_establishment_number_2, :mock_recall_sop_2, :mock_recall_date_2, :recall_this_year_2, :recall_2, :bone_foreign_2, :complaint_2, :problems_2, :haccp_2_certificate, :haccp_2_type, :haccp_2_company, :haccp_2_score, :haccp_2_expires, :haccp_2_scheduled, :usda_establishment_name_3, :usda_establishment_number_3, :mock_recall_sop_3, :mock_recall_date_3, :recall_this_year_3, :recall_3, :bone_foreign_3, :complaint_3, :problems_3, :haccp_3_certificate, :haccp_3_type, :haccp_3_company, :haccp_3_score, :haccp_3_expires, :haccp_3_scheduled, :non_disclosure, :w9, :guarantee, :liability, :additional_string_1, :additional_string_2, :additional_string_3, :additional_string_4, :additional_string_5, :additional_integer_1, :additional_integer_2, :additional_integer_3, :additional_integer_4, :additional_integer_5)
    end
end

app/helpers/packets_helper.rb
module PacketsHelper
end

app/views/packets/_static_fields.html.erb
<p>
  <strong>Packet number:</strong>
  <%= @packet.packet_number %>&emsp;&emsp;
  <strong>Vendor number:</strong>
  <%= @packet.vendor_number %>&emsp;&emsp;
  <strong>Requested date:</strong>
  <%= "2018-01-10" %>&emsp;&emsp;
  <!-- <%= @packet.requested_date %>&emsp;&emsp; -->
  <strong>Due date:</strong>
  <%= "2018-02-09"%>&emsp;&emsp;
  <!-- <%= @packet.due_date %>&emsp;&emsp; -->
</p>

<fieldset>
  <legend><strong>Company</strong></legend>
  <p>
    <strong>Name:</strong>
    <%= @packet.company_name %>&emsp;&emsp;
    <strong>Type:</strong>
    <%= @packet.company_type %>&emsp;&emsp;
    <strong>DBA:</strong>
    <%= @packet.dba %>&emsp;&emsp;
  </p>
  <p>
    <strong>Address 1:</strong>
    <%= @packet.address_1 %>&emsp;&emsp;
    <strong>Address 2:</strong>
    <%= @packet.address_2 %>&emsp;&emsp;
    <strong>City:</strong>
    <%= @packet.city %>&emsp;&emsp;
    <strong>Zip:</strong>
    <%= @packet.zip %>&emsp;&emsp;
    <strong>State:</strong>
    <%= @packet.state %>&emsp;&emsp;
    <strong>Country:</strong>
    <%= @packet.cntry_code %>&emsp;&emsp;
  </p>
</fieldset>

<fieldset>
  <legend><strong>Ship Address</strong></legend>
  <p>
    <strong>Address 1:</strong>
    <%= @packet.ship_address_1 %>&emsp;&emsp;
    <strong>Address 2:</strong>
    <%= @packet.ship_address_2 %>&emsp;&emsp;
    <strong>City:</strong>
    <%= @packet.ship_city %>&emsp;&emsp;
    <strong>Zip:</strong>
    <%= @packet.ship_zip %>&emsp;&emsp;
    <strong>State:</strong>
    <%= @packet.ship_state %>&emsp;&emsp;
  </p>
</fieldset>

app/views/packets/edit.html.erb
<h1>Editing Packet</h1>

<%= render 'form', packet: @packet %>
<% link = '/packets/' + @packet.id.to_s + '/products' %>
<%= link_to 'Product list', link %>

app/views/packets/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Packets</h1>

<table class="mytable" class="display" cellspacing="0" >
  <thead>
    <tr>
      <th>Packet number</th>
      <th>Vendor number</th>
      <th>Requested date</th>
      <th>Due date</th>
      <th>Completed</th>
      <th>Company name</th>
      <th>Show</th>
      <th>Edit</th>
      <% if current_user7.admin? %>
        <th>Destroy</th>
      <% end %>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @packets.each do |packet| %>
      <tr>
        <td><%= packet.packet_number %></td>
        <td><%= packet.vendor_number %></td>
        <td><%= packet.requested_date %></td>
        <td><%= packet.due_date %></td>
        <td><%= packet.completed %></td>
        <td><%= packet.company_name %></td>
        <td><%= link_to 'Show', packet %></td>
        <td><%= link_to 'Edit', edit_packet_path(packet) %></td>
        <% if current_user7.admin? %>
          <td><%= link_to 'Destroy', packet, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<% if current_user7.admin? %>
  <%= link_to 'New Packet', new_packet_path %>
  <%= link_to 'CSV download', packets_path(format: "csv") %>
<% end %>

app/views/packets/new.html.erb
<h1>New Packet</h1>

<%= render 'form', packet: @packet %>

<%= link_to 'Back', packets_path %>

app/views/packets/show.html.erb
<% if current_user7.admin? %>
  <p>
    <strong>Completed:</strong>
    <%= @packet.completed %>&emsp;&emsp;
    <strong>Vendor Completed:</strong>
    <% if @packet.additional_integer_1 == 1 %>
      <%= "true" %>&emsp;&emsp;
    <% else %>
      <%= "false" %>&emsp;&emsp;
    <% end %>
  </p>
<% else %>
  <p>
    <strong>Completed:</strong>
    <% if @packet.additional_integer_1 == 1 %>
      <%= "true" %>&emsp;&emsp;
    <% else %>
      <%= "false" %>&emsp;&emsp;
    <% end %>
    <strong>Products still to complete:</strong> <%= @packet.products.where.not(additional_integer_2: 1).count %>
<% end %>

<%= render partial: 'static_fields' %>
<div id="main">
  <fieldset>
    <legend><strong>Primary Contact</strong></legend>
    <p>
      <strong>Name:</strong>
      <%= @packet.primary_contact %>&emsp;&emsp;
      <strong>Office phone:</strong>
      <%= @packet.phone_1 %>&emsp;&emsp;
      <strong>Mobile phone:</strong>
      <%= @packet.phone_2 %>&emsp;&emsp;
      <strong>Email:</strong>
      <%= @packet.email %>&emsp;&emsp;
      <strong>Fax:</strong>
      <%= @packet.fax %>
    </p>
  </fieldset>

  <fieldset>
    <legend><strong>QA Contact</strong></legend>
    <p>
      <strong>Name:</strong>
      <%= @packet.qa_name %>&emsp;&emsp;
      <strong>Office phone:</strong>
      <%= @packet.qa_phone_1 %>&emsp;&emsp;
      <strong>Mobile phone:</strong>
      <%= @packet.qa_phone_2 %>&emsp;&emsp;
      <strong>Email:</strong>
      <%= @packet.qa_email %>
    </p>
  </fieldset>

  <fieldset>
    <legend><strong>Ops Contact</strong></legend>
    <p>
      <strong>Name:</strong>
      <%= @packet.ops_name %>&emsp;&emsp;
      <strong>Office phone:</strong>
      <%= @packet.ops_phone_1 %>&emsp;&emsp;
      <strong>Mobile phone:</strong>
      <%= @packet.ops_phone_2 %>&emsp;&emsp;
      <strong>Email:</strong>
      <%= @packet.ops_email %>
    </p>
  </fieldset>

  <fieldset>
    <legend><strong>USDA Establishment 1</strong></legend>
    <p>
      <strong>Number:</strong>
      <%= @packet.usda_establishment_number_1 %>&emsp;&emsp;
      <strong>Name:</strong>
      <%= @packet.usda_establishment_name_1 %>&emsp;&emsp;
      <strong>Mock recall SOP:</strong>
      <%= @packet.mock_recall_sop_1 %>&emsp;&emsp;
      <strong>Mock recall date:</strong>
      <%= @packet.mock_recall_date_1 %>&emsp;&emsp;
      <strong>Recall this year:</strong>
      <%= @packet.recall_this_year_1 %>&emsp;&emsp;
      <strong>Recall:</strong>
      <%= @packet.recall_1 %>&emsp;&emsp;
      <strong>Bone/Foreign policy:</strong>
      <%= @packet.bone_foreign_1 %>&emsp;&emsp;
      <strong>Complaint policy:</strong>
      <%= @packet.complaint_1 %>&emsp;&emsp;
    </p>
    <p>
      <strong>HACCP certification:</strong>
      <%= @packet.haccp_1_certificate %>&emsp;&emsp;
      <strong>Expires:</strong>
      <%= @packet.haccp_1_expires %>&emsp;&emsp;
      <strong>Scheduled:</strong>
      <%= @packet.haccp_1_scheduled %>&emsp;&emsp;
      <strong>Third party audit:</strong>
      <%= @packet.problems_2 %>&emsp;&emsp;
      <strong>Type:</strong>
      <%= @packet.haccp_1_type %>&emsp;&emsp;
      <strong>Company:</strong>
      <%= @packet.haccp_1_company %>&emsp;&emsp;
      <strong>Score:</strong>
      <%= @packet.haccp_1_score %>&emsp;&emsp;
      <strong>Expires:</strong>
      <%= @packet.additional_string_1 %>&emsp;&emsp;
      <strong>Scheduled:</strong>
      <%= @packet.additional_string_2 %>&emsp;&emsp;
    </p>
  </fieldset>

  <fieldset>
    <legend><strong>USDA Establishment 2</strong></legend>
    <p>
      <strong>Number:</strong>
      <%= @packet.usda_establishment_number_2 %>&emsp;&emsp;
      <strong>Name:</strong>
      <%= @packet.usda_establishment_name_2 %>&emsp;&emsp;
      <strong>Mock recall SOP:</strong>
      <%= @packet.mock_recall_sop_2 %>&emsp;&emsp;
      <strong>Mock recall date:</strong>
      <%= @packet.mock_recall_date_2 %>&emsp;&emsp;
      <strong>Recall this year:</strong>
      <%= @packet.recall_this_year_2 %>&emsp;&emsp;
      <strong>Recall:</strong>
      <%= @packet.recall_2 %>&emsp;&emsp;
      <strong>Bone/Foreign policy:</strong>
      <%= @packet.bone_foreign_2 %>&emsp;&emsp;
      <strong>Complaint policy:</strong>
      <%= @packet.complaint_2 %>&emsp;&emsp;
    </p>
    <p>
      <strong>HACCP certification:</strong>
      <%= @packet.haccp_2_certificate %>&emsp;&emsp;
      <strong>Expires:</strong>
      <%= @packet.haccp_2_expires %>&emsp;&emsp;
      <strong>Scheduled:</strong>
      <%= @packet.haccp_2_scheduled %>&emsp;&emsp;
      <strong>Third party audit:</strong>
      <%= @packet.problems_3 %>&emsp;&emsp;
      <strong>Type:</strong>
      <%= @packet.haccp_2_type %>&emsp;&emsp;
      <strong>Company:</strong>
      <%= @packet.haccp_2_company %>&emsp;&emsp;
      <strong>Score:</strong>
      <%= @packet.haccp_2_score %>&emsp;&emsp;
      <strong>Expires:</strong>
      <%= @packet.additional_string_3 %>&emsp;&emsp;
      <strong>Scheduled:</strong>
      <%= @packet.additional_string_4 %>&emsp;&emsp;
    </p>
  </fieldset>

  <fieldset>
    <legend><strong>USDA Establishment 3</strong></legend>
    <p>
      <strong>Number:</strong>
      <%= @packet.usda_establishment_number_3 %>&emsp;&emsp;
      <strong>Name:</strong>
      <%= @packet.usda_establishment_name_3 %>&emsp;&emsp;
      <strong>Mock recall SOP:</strong>
      <%= @packet.mock_recall_sop_3 %>&emsp;&emsp;
      <strong>Mock recall date:</strong>
      <%= @packet.mock_recall_date_3 %>&emsp;&emsp;
      <strong>Recall this year:</strong>
      <%= @packet.recall_this_year_3 %>&emsp;&emsp;
      <strong>Recall:</strong>
      <%= @packet.recall_3 %>&emsp;&emsp;
      <strong>Bone/Foreign policy:</strong>
      <%= @packet.bone_foreign_3 %>&emsp;&emsp;
      <strong>Complaint policy:</strong>
      <%= @packet.complaint_3 %>&emsp;&emsp;
    </p>
    <p>
      <strong>HACCP certification:</strong>
      <%= @packet.haccp_3_certificate %>&emsp;&emsp;
      <strong>Expires:</strong>
      <%= @packet.haccp_3_expires %>&emsp;&emsp;
      <strong>Scheduled:</strong>
      <%= @packet.haccp_3_scheduled %>&emsp;&emsp;
      <strong>Third party audit:</strong>
      <%= @packet.qa_phone_1_ext %>&emsp;&emsp;
      <strong>Type:</strong>
      <%= @packet.haccp_3_type %>&emsp;&emsp;
      <strong>Company:</strong>
      <%= @packet.haccp_3_company %>&emsp;&emsp;
      <strong>Score:</strong>
      <%= @packet.haccp_3_score %>&emsp;&emsp;
      <strong>Expires:</strong>
      <%= @packet.additional_string_5 %>&emsp;&emsp;
      <strong>Scheduled:</strong>
      <%= @packet.problems_1 %>&emsp;&emsp;
    </p>
  </fieldset>
  <p>
    <strong>Website:</strong>
    <%= @packet.website %>&emsp;&emsp;
    <strong>Notes:</strong>
    <%= @packet.notes %>&emsp;&emsp;
    <strong>Non-disclosure:</strong>
    <%= @packet.non_disclosure %>&emsp;&emsp;
    <strong>W9:</strong>
    <%= @packet.w9 %>&emsp;&emsp;
    <strong>Guarantee:</strong>
    <%= @packet.guarantee %>&emsp;&emsp;
    <strong>Liability:</strong>
    <%= @packet.liability %>&emsp;&emsp;
  </p>
</div>

<% if current_user7.admin? %>
  <button id="btnPrint">Print Preview</button>
  <br>
  <br>
<% end %>
<%= link_to 'Edit', edit_packet_path(@packet) %>
<% if current_user7.admin? %>
  <%= link_to 'Packet list', packets_path %>
<% end %>
<% link = '/packets/' + @packet.id.to_s + '/products' %>
<%= link_to 'Product list', link %>