config/routes.rb
Rails.application.routes.draw do
  resources :packets do
    collection { post :import }
    resources :products do
      collection { post :import }
    end
  end
  devise_for :user7s, controllers: { registrations: "users/registrations" }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#show'
  get 'home/inactive' => 'home#inactive'
  get 'home/ftpguides' => 'home#ftpguides'
  get 'home/websiteguides' => 'home#websiteguides'
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :packet, :foreign_key => "packet_id"
  validates :product_name, presence: true
  validate :mandatory_validation
  validate :claims_documentation
  validate :bug_validation
  validate :case_piece_validation

  def mandatory_validation
    if additional_integer_2 == 1
      if !species.present?
        errors.add(:species, "is required")
      end
      if !vendor_code.present?
        errors.add(:vendor_code, "is required")
      end
      if !vendor_name.present?
        errors.add(:vendor_name, "is required")
      end
      if !product_photo.present?
        errors.add(:product_photo, "is required")
      end
      if !label_type.present?
        errors.add(:label_type, "is required")
      end
      if !label_details.present?
        errors.add(:label_details, "is required")
      end
      if !label.present?
        errors.add(:label, "is required")
      end
      if !safe.present?
        errors.add(:safe, "is required")
      end
      if !production_date.present?
        errors.add(:production_date, "is required")
      end
      if !prod_to_receipt.present?
        errors.add(:prod_to_receipt, "is required")
      end
      if !shelf_life.present?
        errors.add(:shelf_life, "is required")
      end
      if !storage_temp.present?
        errors.add(:storage_temp, "is required")
      end
      if !allergens.present?
        errors.add(:allergens, "is required")
      end
    end
  end

  def claims_documentation
    if additional_integer_2 == 1 && !errors.any?
      if never.present? && withdrawal.present?
        errors.add(:never, "and withdrawal are mutually exclusive")
      end
      if (never.present? || withdrawal.present?) && !never_doc.present?
        errors.add(:never_doc, "is required")
      end
      if withdrawal.present? && !withdrawal_days.present?
        errors.add(:withdrawal_days, "is required")
      end
      if gmo_free.present? && !gmo_free_doc.present?
        errors.add(:gmo_free_doc, "is required")
      end
      if organic.present? && !organic_doc.present?
        errors.add(:organic_doc, "is required")
      end
      if vaccinated.present? && !vaccinated_doc.present?
        errors.add(:vaccinated_doc, "is required")
      end
      if vaccinated.present? && vaccinated_age == 0
        errors.add(:vaccinated_age, "is required")
      end
      if humane.present? && !humane_doc.present?
        errors.add(:humane_doc, "is required")
      end
      if traceable.present? && !traceable_doc.present?
        errors.add(:traceable_doc, "is required")
      end
      if (sqft_inside > 0 || sqft_outside > 0 || sqft_total > 0) && !sqft_doc.present?
        errors.add(:sqft_doc, "is required")
      end
      if pastured.present? && !pastured_doc.present?
        errors.add(:pastured_doc, "is required")
      end
      if omega3.present? && !omega3_doc.present?
        errors.add(:omega3_doc, "is required")
      end
      if vegetable.present? && !vegetable_doc.present?
        errors.add(:vegetable_doc, "is required")
      end
      if additional_integer_3 == 1 && !other_doc.present?
      # other_claims was not created as a boolean so does not work
        errors.add(:other_doc, "is required")
      end
    end
  end

  def bug_validation
    if additional_integer_2 == 1 && !errors.any?
      if additional_integer_1 == 1 && !bug.present?
        errors.add(:bug, "documentation is required")
      end
      if additional_integer_1 == 1 && !usda_approve.present?
        errors.add(:usda_approve, "documentation is required")
      end
    end
  end

  def case_piece_validation
    if additional_integer_2 == 1 && !errors.any?
      if case_piece.present?
        # box
        if !box_type.present?
          errors.add(:box_type, "is required")
        end
        if !box_details.present?
          errors.add(:box_details, "is required")
        end
        if !box_units.present?
          errors.add(:box_units, "is required")
        end
        if !box_length.present?
          errors.add(:box_length, "is required")
        end
        if !box_width.present?
          errors.add(:box_width, "is required")
        end
        if !box_height.present?
          errors.add(:box_height, "is required")
        end
        if !box_count.present?
          errors.add(:box_count, "is required")
        end
        if !piece_count.present?
          errors.add(:piece_count, "is required")
        end
        if !package_photo?
          errors.add(:package_photo, "is required")
        end
      else
        # piece
        if !piece_box.present?
          errors.add(:piece_box, "is required")
        end
        if !piece_pack.present?
          errors.add(:piece_pack, "is required")
        end
        if !piece_count.present?
          errors.add(:piece_count, "is required")
        end
        if !package_photo?
          errors.add(:package_photo, "is required")
        end
      end
    end
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :load_packet
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = @packet.products.all
  end

  # GET /products/1
  def show
  end

  # GET /products/new
  def new
    @product = @packet.products.new
    @products = @packet.products.all
  end

  # GET /products/1/edit
  def edit
    @products = @packet.products.all
  end

  # POST /products
  def create
    @product = @packet.products.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to [@packet, @product], notice: 'Product was successfully created.' }
      else
        format.html { render :new }
      end
    end
  end

  # PATCH/PUT /products/1
  def update
    @products = @packet.products.all
    if params[:product][:additional_string_1].present?
      # The user wants to copy another product's data
      @from = Product.where(product_code: params[:product][:additional_string_1], packet_id: @product.packet_id).first
      params[:product][:species] = @from.species
      params[:product][:box] = @from.box
      params[:product][:box_type] = @from.box_type
      params[:product][:box_details] = @from.box_details
      params[:product][:box_units] = @from.box_units
      params[:product][:box_length] = @from.box_length
      params[:product][:box_width] = @from.box_width
      params[:product][:box_height] = @from.box_height
      params[:product][:box_count] = @from.box_count
      params[:product][:piece_box] = @from.piece_box
      params[:product][:piece_pack] = @from.piece_pack
      params[:product][:piece_count] = @from.piece_count
      params[:product][:package_photo] = @from.package_photo
      params[:product][:label] = @from.label
      params[:product][:label_type] = @from.label_type
      params[:product][:label_details] = @from.label_details
      params[:product][:safe] = @from.safe
      params[:product][:weight_units] = @from.weight_units
      params[:product][:weight_max] = @from.weight_max
      params[:product][:weight_min] = @from.weight_min
      params[:product][:product_photo] = @from.product_photo
      params[:product][:bug] = @from.bug
      params[:product][:production_date] = @from.production_date
      params[:product][:pallet_layers] = @from.pallet_layers
      params[:product][:pallet_count_per_layer] = @from.pallet_count_per_layer
      params[:product][:pallet_length] = @from.pallet_length
      params[:product][:pallet_height] = @from.pallet_height
      params[:product][:pallet_width] = @from.pallet_width
      params[:product][:never] = @from.never
      params[:product][:never_doc] = @from.never_doc
      params[:product][:withdrawal] = @from.withdrawal
      params[:product][:withdrawal_doc] = @from.withdrawal_doc
      params[:product][:withdrawal_days] = @from.withdrawal_days
      params[:product][:gmo_free] = @from.gmo_free
      params[:product][:gmo_free_doc] = @from.gmo_free_doc
      params[:product][:organic] = @from.organic
      params[:product][:organic_doc] = @from.organic_doc
      params[:product][:vaccinated] = @from.vaccinated
      params[:product][:vaccinated_age] = @from.vaccinated_age
      params[:product][:vaccinated_doc] = @from.vaccinated_doc
      params[:product][:humane] = @from.humane
      params[:product][:humane_doc] = @from.humane_doc
      params[:product][:traceable] = @from.traceable_doc
      params[:product][:traceable_doc] = @from.traceable_doc
      params[:product][:sqft_doc] = @from.sqft_doc
      params[:product][:sqft_total] = @from.sqft_total
      params[:product][:sqft_inside] = @from.sqft_inside
      params[:product][:sqft_outside] = @from.sqft_outside
      params[:product][:pallet_layers] = @from.pallet_layers
      params[:product][:pastured] = @from.pastured
      params[:product][:pastured_doc] = @from.pastured_doc
      params[:product][:omega3] = @from.omega3
      params[:product][:omega3_doc] = @from.omega3_doc
      params[:product][:vegetable] = @from.vegetable
      params[:product][:vegetable_doc] = @from.vegetable_doc
      params[:product][:other_doc] = @from.other_doc
      params[:product][:other_claims] = @from.other_claims
      params[:product][:prod_to_receipt] = @from.prod_to_receipt
      params[:product][:shelf_life] = @from.shelf_life
      params[:product][:production_changes] = @from.production_changes
      params[:product][:storage_temp] = @from.storage_temp
      params[:product][:microbe] = @from.microbe
      params[:product][:physical] = @from.physical
      params[:product][:vendor_spec] = @from.vendor_spec
      params[:product][:usda_approve] = @from.usda_approve
      params[:product][:allergens] = @from.allergens
      params[:product][:additional_integer_1] = @from.additional_integer_1
    end
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to [@packet, @product], notice: 'Product was successfully updated.' }
      else
        format.html { render :edit }
      end
    end
  end

  # DELETE /products/1
  def destroy
    respond_to do |format|
      if @product.destroy
        format.html { redirect_to packet_products_path(@packet), notice: 'Product was successfully destroyed.' }
      end
    end
  end

  # def import
    # Product.import(params[:file])
    # redirect_to root_url, notice: "Products imported."
  # end

  private
    # Use callbacks to share common setup or constraints between actions.
    def load_packet
      @packet = Packet.find(params[:packet_id])
      unless current_user7.id == @packet.user_id || current_user7.admin?
       redirect_to root_path, :alert => "Access denied."
      end
    end

    def set_product
      @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:packet_id, :species, :product_name, :product_code, :vendor_code, :vendor_name, :case_piece, :box, :box_type, :box_details, :box_units, :box_length, :box_width, :box_height, :box_count, :piece_box, :piece_pack, :piece_count, :package_photo, :label, :label_type, :label_details, :safe, :weight_units, :weight_max, :weight_target, :weight_min, :product_photo, :bug, :production_date, :pallet_layers, :pallet_count_per_layer, :pallet_length, :pallet_width, :pallet_height, :never, :never_doc, :withdrawal, :withdrawal_doc, :withdrawal_days, :gmo_free, :gmo_free_doc, :organic, :organic_doc, :vaccinated, :vaccinated_doc, :vaccinated_age, :humane, :humane_doc, :traceable, :traceable_doc, :sqft_inside, :sqft_outside, :sqft_total, :sqft_doc, :pastured, :pastured_doc, :omega3, :omega3_doc, :vegetable, :vegetable_doc, :other_claims, :other_doc, :prod_to_receipt, :shelf_life, :production_changes, :storage_temp, :microbe, :physical, :vendor_spec, :usda_approve, :allergens, :additional_string_1, :additional_string_2, :additional_string_3, :additional_string_4, :additional_string_5, :additional_integer_1, :additional_integer_2, :additional_integer_3, :additional_integer_4, :additional_integer_5)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/edit.html.erb
<h1>Editing Product</h1>
<%= render 'form', product: @product %>

<%= link_to 'Show', packet_product_path(@packet, @product) %>
<%= link_to 'Product list', packet_products_path %>
<% link = '/packets/' + @packet.id.to_s %>
<%= link_to 'Show Packet', link %>

app/views/products/index.html.erb
<h1>Products</h1>

<table class="mytable" class="display" cellspacing="0" >
  <thead>
    <tr>
      <th>Product name</th>
      <th>Product code</th>
      <th>Show</th>
      <th>Edit</th>
      <% if current_user7.admin? %>
        <th>Destroy</th>
      <% end %>
      <th>Completed?</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @products.each do |product| %>
      <% if !product.product_name.include? "INACTIVE" %>
        <% @product = product %>
        <tr>
          <td><%= @product.product_name %></td>
          <td><%= @product.product_code %></td>
          <td><%= link_to 'Show', packet_product_path(@packet, @product) %></td>
          <td><%= link_to 'Edit', edit_packet_product_path(@packet, @product) %></td>
          <% if current_user7.admin? %>
            <td><%= link_to 'Destroy', [@packet, @product], method: :delete, data: { confirm: 'Are you sure?' } %></td>
          <% end %>
          <% if @product.additional_integer_2 == 1 %>
            <td><%= "true" %></td>
          <% else %>
            <td><%= "false" %></td>
          <% end %>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>

<br>

<% if current_user7.admin? %>
  <%= link_to 'New Product', new_packet_product_path(@packet) %>
<% end %>
<% link = '/packets/' + @packet.id.to_s %>
<%= link_to 'Show Packet', link %>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', packet: @packet, product: @product %>

<%= link_to 'Back', packet_products_path(@packet) %>

app/views/products/show.html.erb
<strong>Completed:</strong>
  <% if @product.additional_integer_2 == 1 %>
    <%= "true" %>
  <% else %>
    <%= "false" %>
  <% end %>

<p>
  <strong>Packet number:</strong>
  <%= @packet.packet_number %>
</p>

<div id="main">
  <p>
    <strong>Species/Breed:</strong>
    <%= @product.species %>&emsp;&emsp;
    <strong>Product code:</strong>
    <%= @product.product_code %>&emsp;&emsp;
    <strong>Product description:</strong>
    <%= @product.product_name %>&emsp;&emsp;
    <strong>Vendor code:</strong>
    <%= @product.vendor_code %>&emsp;&emsp;
    <strong>Vendor description:</strong>
    <%= @product.vendor_name %>&emsp;&emsp;
    <strong>Product photo:</strong>
    <%= @product.product_photo %>
  </p>

  <% if @product.case_piece %>
    <fieldset>
      <legend><strong>Box</strong></legend>
      <p>
        <strong>Type:</strong>
        <%= @product.box_type %>&emsp;&emsp;
        <strong>Details:</strong>
        <%= @product.box_details %>&emsp;&emsp;
        <strong>Units:</strong>
        <%= @product.box_units %>&emsp;&emsp;
        <strong>Length:</strong>
        <%= @product.box_length %>&emsp;&emsp;
        <strong>Width:</strong>
        <%= @product.box_width %>&emsp;&emsp;
        <strong>Height:</strong>
        <%= @product.box_height %>&emsp;&emsp;
        <strong>Pieces per box:</strong>
        <%= @product.box_count %>&emsp;&emsp;
        <strong>Items per piece:</strong>
        <%= @product.piece_count %>&emsp;&emsp;
        <strong>Photo:</strong>
        <%= @product.package_photo %>
      </p>
    </fieldset>
  <% else %>
    <fieldset>
      <legend><strong>Piece</strong></legend>
      <p>
        <strong>Box:</strong>
        <%= @product.piece_pack %>&emsp;&emsp;
        <strong>Pack:</strong>
        <%= @product.piece_box %>&emsp;&emsp;
        <strong>Items per piece:</strong>
        <%= @product.piece_count %>&emsp;&emsp;
        <strong>Photo:</strong>
        <%= @product.package_photo %>
      </p>
    </fieldset>
  <% end %>

  <fieldset>
    <legend><strong>Label</strong></legend>
    <p>
      <strong>Type:</strong>
      <%= @product.label_type %>&emsp;&emsp;
      <strong>Details:</strong>
      <%= @product.label_details %>&emsp;&emsp;
      <strong>Documentation:</strong>
      <%= @product.label %>&emsp;&emsp;
      <strong>Safe handling:</strong>
      <%= @product.safe %>&emsp;&emsp;
      <strong>Bug:</strong>
      <% if @product.additional_integer_1 == 1 %>
        <%= "true" %>&emsp;&emsp;
      <% else %>
        <%= "false" %>&emsp;&emsp;
      <% end %>
      <strong>Documentation:</strong>
      <%= @product.bug %>&emsp;&emsp;
     </p>
  </fieldset>

  <fieldset>
    <legend><strong>Weight</strong></legend>
    <p>
      <strong>Units:</strong>
      <%= @product.weight_units %>&emsp;&emsp;
      <strong>Max:</strong>
      <%= @product.weight_max %>&emsp;&emsp;
      <strong>Min:</strong>
      <%= @product.weight_min %>&emsp;&emsp;
    </p>
  </fieldset>

  <fieldset>
    <legend><strong>Pallet</strong></legend>
    <p>
      <strong>Number of layers:</strong>
      <%= @product.pallet_layers %>&emsp;&emsp;
      <strong>Boxes per layer:</strong>
      <%= @product.pallet_count_per_layer %>&emsp;&emsp;
      <strong>Length:</strong>
      <%= @product.pallet_length %>&emsp;&emsp;
      <strong>Width:</strong>
      <%= @product.pallet_width %>&emsp;&emsp;
      <strong>Height:</strong>
      <%= @product.pallet_height %>&emsp;&emsp;
    </p>
  </fieldset>
  <fieldset>
    <legend><strong>Claims</strong></legend>
    <p>
      <strong>Antibiotic free:</strong><br>
      <strong>Never ever:</strong>
      <%= @product.never %>&emsp;&emsp;
      <strong>Withdrawal:</strong>
      <%= @product.withdrawal %>&emsp;&emsp;
      <strong>Number of days:</strong>
      <%= @product.withdrawal_days %>&emsp;&emsp;
      <strong>Documentation:</strong>
      <%= @product.never_doc %>&emsp;&emsp;
      <strong>GMO free:</strong>
      <%= @product.gmo_free %>&emsp;&emsp;
      <strong>Documentation:</strong>
      <%= @product.gmo_free_doc %>&emsp;&emsp;
      <strong>Organic certification:</strong>
      <%= @product.organic %>&emsp;&emsp;
      <strong>Documentation:</strong>
      <%= @product.organic_doc %>&emsp;&emsp;
      <strong>Vaccinated:</strong>
      <%= @product.vaccinated %>&emsp;&emsp;
      <strong>Age:</strong>
      <%= @product.vaccinated_age %>&emsp;&emsp;
      <strong>Documentation:</strong>
      <%= @product.vaccinated_doc %>&emsp;&emsp;
    </p>
    <p>
      <strong>Humanely raised certification:</strong>
      <%= @product.humane %>&emsp;&emsp;
      <strong>Documentation:</strong>
      <%= @product.humane_doc %>&emsp;&emsp;
      <strong>Traceability to farm:</strong>
      <%= @product.traceable %>&emsp;&emsp;
      <strong>Documentation:</strong>
      <%= @product.traceable_doc %>&emsp;&emsp;
      <strong>Sqft inside:</strong>
      <%= @product.sqft_inside %>&emsp;&emsp;
      <strong>Sqft outside:</strong>
      <%= @product.sqft_outside %>&emsp;&emsp;
      <strong>Sqft total:</strong>
      <%= @product.sqft_total %>&emsp;&emsp;
      <strong>Documentation:</strong>
      <%= @product.sqft_doc %>&emsp;&emsp;
    </p>
    <p>
      <strong>Pastured:</strong>
      <%= @product.pastured %>&emsp;&emsp;
      <strong>Documentation:</strong>
      <%= @product.pastured_doc %>&emsp;&emsp;
      <strong>Omega3:</strong>
      <%= @product.omega3 %>&emsp;&emsp;
      <strong>Documentation:</strong>
      <%= @product.omega3_doc %>&emsp;&emsp;
      <strong>Vegetable fed:</strong>
      <%= @product.vegetable %>&emsp;&emsp;
      <strong>Documentation:</strong>
      <%= @product.vegetable_doc %>&emsp;&emsp;
      <strong>Other:</strong>
      <% if @product.additional_integer_3 == 1 %>
        <%= "true" %>&emsp;&emsp;
      <% else %>
        <%= "false" %>&emsp;&emsp;
      <% end %>
      <strong>Documentation:</strong>
      <%= @product.other_doc %>&emsp;&emsp;
    </p>
  </fieldset>

  <fieldset>
    <legend><strong>Storage</strong></legend>
    <p>
      <strong>Production date(location/format):</strong>
      <%= @product.production_date %>&emsp;&emsp;
      <strong>Max days production to receipt:</strong>
      <%= @product.prod_to_receipt %>&emsp;&emsp;
      <strong>Shelf life(days):</strong>
      <%= @product.shelf_life %>&emsp;&emsp;
      <strong>Storage temp:</strong>
      <%= @product.storage_temp %>&emsp;&emsp;
      <strong>Microbiological support:</strong>
      <%= @product.microbe %>&emsp;&emsp;
      <strong>Physical sensory study support:</strong>
      <%= @product.physical %>&emsp;&emsp;
    </p>
  </fieldset>

  <fieldset>
    <legend><strong>Other</strong></legend>
    <p>
      <strong>Vendor Specification:</strong>
      <%= @product.vendor_spec %>&emsp;&emsp;
      <strong>USDA approval:</strong>
      <%= @product.usda_approve %>&emsp;&emsp;
      <strong>Allergens:</strong>
      <%= @product.allergens %>&emsp;&emsp;
    </p>
  </fieldset>
</div>
<br>
<% if current_user7.admin? %>
  <button id="btnPrint">Print Preview</button>
  <br>
  <br>
<% end %>
<%= link_to 'Edit', edit_packet_product_path(@packet, @product) %>
<%= link_to 'Product list', packet_products_path(@packet) %>
<% link = '/packets/' + @packet.id.to_s %>
<%= link_to 'Show Packet', link %>