config/routes.rb
Rails.application.routes.draw do
  resources :packets do
    collection { post :import }
    resources :products do
      collection { post :import }
    end
  end
  devise_for :user7s, controllers: { registrations: "users/registrations" }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'home#show'
  get 'home/inactive' => 'home#inactive'
  get 'home/ftpguides' => 'home#ftpguides'
  get 'home/websiteguides' => 'home#websiteguides'
end

app/views/layouts/_header.html.erb
<h2 class="primary-logo">
</h2>
<nav class="">
    <ul>
        <%= render partial: 'layouts/sign_in' %>
        <%= content_tag(:div, flash[:error], :id => "flash_error") if flash[:error] %>
        <%= content_tag(:div, flash[:notice], :id => "flash_notice") if flash[:notice] %>
        <%= content_tag(:div, flash[:alert], :id => "flash_alert") if flash[:alert] %>
    </ul>
</nav>
<br>

app/views/layouts/_sign_in.html.erb
<% if user7_signed_in? %>
  <span>Signed in as <%= current_user7.email %></span>
<% else %>
  <span>No user currently signed in</span>
<% end %>
<span id="navbar">
  <% if user7_signed_in? %>
    <span><a href="/home/ftpguides">Upload Guide</a></span>
    <span><a href="/home/websiteguides">Website Guide</a></span>
    <span><a href="ftp://10.0.0.190" target="_blank">Upload</a></span>
    <span><a href="/">Home</a></span>
    <span><%= link_to 'Sign out', destroy_user7_session_path, method: :delete %></span>
    <% if current_user7.admin? %>
      <span><%= link_to 'Edit user', edit_user7_registration_path %></span>
      <span><%= link_to 'Sign up', new_user7_registration_path %></span>
      <span><a href="/home/inactive">Inactive</a></span>
    <% end %>
  <% else %>
    <span><%= link_to 'Sign in', new_user7_session_path %></span>
  <% end %>
</span>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>VendorPackets</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div style="position: fixed; top: 0px; width: 100%; height: 8em; background-color: white; z-index: 100;">
      <%= render 'layouts/header' %>
    </div>
    <div style="margin-top: 8.5em;">
      <%= yield %>
    </div>
    <script src="//ajax.googleapis.com/ajax/libs/jquery/1.11.2/jquery.min.js"></script>
    <script src="//ajax.googleapis.com/ajax/libs/jqueryui/1.11.2/jquery-ui.min.js"></script>
    <script src="//code.jquery.com/jquery-1.12.4.js"></script>
    <script src="//cdn.datatables.net/1.10.16/js/jquery.dataTables.min.js"></script>
    <script src="//cdn.datatables.net/buttons/1.4.2/js/dataTables.buttons.min.js"></script>
    <script src="//cdn.datatables.net/buttons/1.4.2/js/buttons.print.min.js"></script>
    <script src="//www.flotcharts.org/flot/jquery.flot.js"></script>
    <script src="//www.flotcharts.org/flot/jquery.flot.pie.js"></script>
    <script src="/assets/printPreview.js"></script>
    <script src="/assets/myjavascript.js"></script>
    <script>
      $(document).ready(function() {

        function getData(data)
        {
          var p1 = data.replace('[', "");
          var p2 = p1.replace(']', "");
          p1 = p2.replace(/,/g, "");
          var data_array = p1.split(" ");
          data_array.shift();
          data_array.pop();
          return data_array;
        }

        function pieChart()
          {
          //******* Month to date late order pie chart
          var percentages = document.getElementById("percentages").innerHTML;
          var percent_array = getData(percentages);
          var labels = ["0%", "1-20%", "21-40%", "41-60%", "61-80%", "81-100%"]
          var dataset = [];
          var length = percent_array.length;
          var i = 0;
          for (i = 0; i < length; i++) {
            dataset[i] = {
              label: labels[i],
              data: percent_array[i]
            }
          }

          var options = {
            series: {
                pie: {
                    show: true
                }
            },
            grid: {
              clickable: true,
              hoverable: true
            }
          }
          $.plot($("#flot-piechart"), dataset, options);
        }

        function showToolTip(contents) {
          $('<div id="tooltip">' + contents + '</div>').css( {
            position: 'relative', display: 'none'
          }).appendTo('#mypie').fadeIn(200);
        }

        function showSliceOfPie(ven_code, ven_name, pcent, packet_id) {
          var mypie = document.getElementById('pietable');
          var tit = document.createElement('h3');
          tit.setAttribute("id","pieface");
          var h3Text = document.createTextNode("Vendors completing " + pcent + " of their packet");
          tit.appendChild(h3Text);
          var tbl = document.createElement('table');
          tbl.setAttribute("id","sliceofpie");
          tbl.setAttribute("class","mytable");
          var row = document.createElement('tr');
          var headerCell = document.createElement("th");
          var cellText = document.createTextNode('Vendor number');
          headerCell.appendChild(cellText);
          row.appendChild(headerCell);
          var headerCell = document.createElement("th");
          var cellText = document.createTextNode('Name');
          headerCell.appendChild(cellText);
          row.appendChild(headerCell);
          var headerCell = document.createElement("th");
          var cellText = document.createTextNode('Show Packet');
          headerCell.appendChild(cellText);
          row.appendChild(headerCell);
          tbl.appendChild(row);
          var length = ven_name.length
          //Add the data rows.
          for (var i = 0; i < length; i++) {
            var row = document.createElement("tr");
            var cell = document.createElement("td");
            var cellText = document.createTextNode(ven_code[i]);
            cell.appendChild(cellText);
            row.appendChild(cell);
            var cell = document.createElement("td");
            company_name = ven_name[i].replace(/"/g, '')
            var cellText = document.createTextNode(company_name.replace(/~/g, ' '));
            cell.appendChild(cellText);
            row.appendChild(cell);
            var cell = document.createElement("td");
            var a = document.createElement('a');
            var linkText = document.createTextNode("Show");
            a.appendChild(linkText);
            a.title = "Show vendor packet";
            a.href = "/packets/" + packet_id[i];
            cell.appendChild(a);
            row.appendChild(cell);
            tbl.appendChild(row);
          }
          mypie.appendChild(tit);
          mypie.appendChild(tbl);
        }

        $("#flot-piechart").bind("plotclick", function (event, pos, item) {
          $('#pieface').remove();
          $('#sliceofpie').remove();
          if (item) {
            switch (item.series.label) {
              case '0%':
                var pie_code = document.getElementById("percent0code").innerHTML;
                var pie_name = document.getElementById("percent0name").innerHTML;
                var packets = document.getElementById("percent0packet").innerHTML;
                break;
              case '1-20%':
                var pie_code = document.getElementById("percent20code").innerHTML;
                var pie_name = document.getElementById("percent20name").innerHTML;
                var packets = document.getElementById("percent20packet").innerHTML;
                break;
              case '21-40%':
                var pie_code = document.getElementById("percent40code").innerHTML;
                var pie_name = document.getElementById("percent40name").innerHTML;
                var packets = document.getElementById("percent40packet").innerHTML;
                break;
              case '41-60%':
                var pie_code = document.getElementById("percent60code").innerHTML;
                var pie_name = document.getElementById("percent60name").innerHTML;
                var packets = document.getElementById("percent80packet").innerHTML;
                break;
              case '61-80%':
                var pie_code = document.getElementById("percent80code").innerHTML;
                var pie_name = document.getElementById("percent80name").innerHTML;
                var packets = document.getElementById("percent80packet").innerHTML;
                break;
              default:
                var pie_code = document.getElementById("percent100code").innerHTML;
                var pie_name = document.getElementById("percent100name").innerHTML;
                var packets = document.getElementById("percent100packet").innerHTML;
            }
          }
          var ven_code = getData(pie_code);
          var ven_name = getData(pie_name);
          var packet_id = getData(packets);
          showSliceOfPie(ven_code, ven_name, item.series.label, packet_id);
        });

        $("#flot-piechart").bind("plothover", function (event, pos, item) {
          $('#tooltip').remove();
          if (item) {
            switch (item.series.label) {
              case '0%':
                var pie_code = document.getElementById("percent0code").innerHTML;
                break;
              case '1-20%':
                var pie_code = document.getElementById("percent20code").innerHTML;
                break;
              case '21-40%':
                var pie_code = document.getElementById("percent40code").innerHTML;
                break;
              case '41-60%':
                var pie_code = document.getElementById("percent60code").innerHTML;
                break;
              case '61-80%':
                var pie_code = document.getElementById("percent80code").innerHTML;
                break;
              default:
                var pie_code = document.getElementById("percent100code").innerHTML;
            }
            var ven_code = getData(pie_code);
            showToolTip(ven_code.length + " vendors have completed " + item.series.label + " of their packet.");
          }
        });

        $('.mytable').DataTable({
          scrollY: "400px",
          scrollCollapse: true,
          paging: false,
          autoWidth: true,
          responsive: true,
          retrieve: true,
          buttons: [
            'print'
          ]
        });
        $("#fadetoggle1").change(function(){
            $("#usda2").toggle(1000);
        });
        $("#fadetoggle2").change(function(){
            $("#usda3").toggle(1000);
        });
        $("#btnPrint").printPreview({
          obj2print:'#main'
        });

        pieChart();

      });
    </script>
    <style media="screen">
      body {
        background-color: #fff;
        color: #333;
        margin: 3px;
        font-family: verdana, arial, helvetica, sans-serif;
        font-size: 13px;
        line-height: 18px;
      }

      p, ol, ul, td {
        font-family: verdana, arial, helvetica, sans-serif;
        font-size: 13px;
        line-height: 18px;
      }

      pre {
        background-color: #eee;
        padding: 10px;
        font-size: 11px;
      }

      a:link, a:visited {
          background-color: white;
          color: black;
          border: 2px solid black;
          border-radius: 4px;
          padding: 5px 5px;
          text-align: center;
          text-decoration: none;
          display: inline-block;
      }

      a:hover, a:active {
          background-color: black;
          color: white;
          box-shadow: 5px 10px 8px #888888;
      }

      table, th, td {
          border: 0px solid black;
          border-collapse: collapse;
      }

      th, td {
        padding: 1px;
        text-align: left;
      }

      th{
        text-align: left;
        background-color: black;
        color: white;
      }

      tr:nth-child(even){
        background-color: #d6d6d6;
      }

      div {
        &.field, &.actions {
          margin-bottom: 10px;
        }
      }

      .title {
        text-align: center;
        float: left;
        margin-left: 1em;
        margin-right: 1em;
      }

      .primary-logo {
        margin: 0;
        width: 5.5em;
        height: 3em;
        float: left;
        position: relative;
        background: image-url("/assets/DArtagnan_Logo_2015_CMYK_micro.jpg");
      }

      #notice {
        color: green;
      }

      #flash_notice {
        color: green;
      }

      #flash_alert {
        color: rgb(255,128,0);
      }

      #flash_error {
        color: rgb(255,153,153);
      }

      .field_with_errors {
        padding: 2px;
        background-color: red;
        display: table;
      }

      #error_explanation {
        width: 450px;
        border: 2px solid red;
        padding: 7px 7px 0;
        margin-bottom: 20px;
        background-color: #f0f0f0;

        h2 {
          text-align: left;
          font-weight: bold;
          padding: 5px 5px 5px 15px;
          font-size: 12px;
          margin: -7px -7px 0;
          background-color: #c00;
          color: #fff;
        }

        ul li {
          font-size: 12px;
          list-style: square;
        }
      }

      label {
        display: block;
      }

      #althead {
        text-align: left;
        background-color: black;
        color: white;
      }

      #navbar span {
        float: left;
        margin-right: 1em;
      }
      .dropbtn {
        background-color: white;
        color: black;
        border: 2px solid black;
        border-radius: 4px;
        padding: 5px 5px;
        text-align: center;
        text-decoration: none;
        display: inline-block;
        float: left;
        display: inline-block;
      }

      .dropdown {
          position: relative;
          display: inline-block;
      }

      .dropdown-content {
          display: none;
          position: absolute;
          min-width: 45px;
          z-index: 1;
      }

      .dropdown-content span {
          color: black;
          text-decoration: none;
          display: block;
      }

      /* .dropdown-content span:hover {background-color: rgb(255,255,102)} */

      .dropdown:hover .dropdown-content {
          display: block;
      }
    </style>
  </body>
</html>